version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_movie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_movie_db?sslmode=disable
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
